insert INTO SAMPLE VALUES (999, 'JOHN SMITH');

--placeholder DO NOT DELETE--
INSERT INTO USERS (USER_ID, USER_NAME) VALUES (0, 'default');
INSERT INTO DEVICES (DEVICE_ID, USER_ID) VALUES (0,0);
INSERT INTO CHANNELS (CHANNEL_ID) VALUES (0);
INSERT INTO MESSAGES (MESSAGE_ID) VALUES (0);
-----------------------------

INSERT INTO USERS VALUES (500, 'JOHN SMITH', 'example@company.com','Last login on 99/99/9999','END_USER');
INSERT INTO USERS VALUES (501, 'JOHN SMITH', 'example@company.com','Last login on 99/99/9999','MANAGER');
INSERT INTO USERS VALUES (502, 'ALEX LAWRENCE', 'example@company.com', 'Last login on 99/99/9999','END_USER');
INSERT INTO DEVICES VALUES (400,500, 'JOHN SMITH');
INSERT INTO DEVICES VALUES (401,501, 'JOHN SMITH');
INSERT INTO CHANNELS VALUES (300, 'WEATHER', 'Weather', 'Marietta, GA', 5000, 'SLIDE');
INSERT INTO MESSAGES VALUES (200, 'The pool house will be closed', 0);

--(groupid, userid, deviceid, channelid, messageid)
INSERT INTO GROUPS VALUES (900, 500, 0, 0, 0);
INSERT INTO GROUPS VALUES (900, 501, 0, 0, 0);
INSERT INTO GROUPS VALUES (900, 0, 400, 0, 0);
INSERT INTO GROUPS VALUES (900, 0, 401, 0, 0);
INSERT INTO GROUPS VALUES (900, 0, 0, 300, 0);
INSERT INTO GROUPS VALUES (900, 0, 400, 0, 200);