CREATE TABLE USERS(
USER_ID NUMBER(9) NOT NULL,
USER_NAME VARCHAR(20),
EMAIL VARCHAR(254),
LOGIN_DETAIL VARCHAR,
USER_TYPE VARCHAR(10),
PRIMARY KEY (USER_ID)
);

CREATE TABLE DEVICES(
DEVICE_ID NUMBER(9) NOT NULL,
USER_ID NUMBER(9),
USER_NAME VARCHAR(20),
MESSAGE_ID NUMBER(9),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY (MESSAGE_ID)
PRIMARY KEY (DEVICE_ID),
);

CREATE TABLE CHANNELS(
CHANNEL_ID NUMBER(9),
CHANNEL_NAME VARCHAR(20),
TITLE VARCHAR(20),
TEXT VARCHAR(1000),
REFRESH_TIME NUMBER(12),
CHANNEL_TYPE VARCHAR(10),
PRIMARY KEY (CHANNEL_ID)
);

CREATE TABLE MESSAGES(
MESSAGE_ID NUMBER(9),
TEXT VARCHAR(1000),
PRIORITY NUMBER(9),
PRIMARY KEY (MESSAGE_ID)
);

CREATE TABLE GROUPS(
GROUP_ID NUMBER(9) NOT NULL,
USER_ID NUMBER(9),
DEVICE_ID NUMBER(9),
CHANNEL_ID NUMBER(9),
MESSAGE_ID NUMBER(9),
FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES(DEVICE_ID),
FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(CHANNEL_ID),
FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES(MESSAGE_ID),
PRIMARY KEY (GROUP_ID, USER_ID, DEVICE_ID, CHANNEL_ID, MESSAGE_ID)
);

CREATE SEQUENCE USER_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE GROUP_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE CHANNEL_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE MESSAGE_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE DEVICE_SEQUENCE
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999999
    NOCACHE
    NOCYCLE;



CREATE TABLE SAMPLE(
ID NUMBER(9) NOT NULL,
NAME VARCHAR(10)
);